version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: docker/dockerfile
    container_name: node_backend
    restart: always
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: npm start

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "3000:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
