FROM node:23-slim

# Instala netcat Y mysql-client (necesario para mysqladmin)
RUN apt-get update && \
    apt-get install -y netcat-openbsd default-mysql-client && \
    apt-get clean

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Solo necesitamos entrypoint.sh ahora
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]