FROM node:23-slim

# Instala netcat y cliente MySQL (útil para debugging)
RUN apt-get update && \
    apt-get install -y netcat-openbsd default-mysql-client && \
    apt-get clean

WORKDIR /app

# Copia package.json + lock para aprovechar cache
COPY package*.json ./

RUN npm install
RUN npm install -g nodemon

# Copia todo el código del backend (incluyendo prisma/)
COPY . .

# Genera cliente Prisma una vez copiado el schema
RUN npx prisma generate

EXPOSE 5000

CMD ["npm", "run", "dev"]
