FROM node:23-slim

# Instala netcat y cliente MySQL (si en algún punto querés debuggear o testear conexiones manualmente)
RUN apt-get update && \
    apt-get install -y netcat-openbsd default-mysql-client && \
    apt-get clean

# Crea el directorio de trabajo
WORKDIR /app

# Copia primero los package.json para aprovechar cache en builds
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon

# Copia el resto del proyecto
COPY . .

# Expone el puerto en el que corre tu API
EXPOSE 5000

# Comando de arranque
CMD ["npm", "start"]
